name: gophermart test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        run: |
          brew install go-task
          task lint

      - name: Run test
        run: |
          cd ./internal/gophermart/handlers
          go test -cover
      

