name: gophermart test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          task install-linter

      - name: Run linter
        run: |
          task lint

      - name: Run test
        run: |
          task test
#          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
#          task install-linter
          


